---
# tasks file for ansible-role-rtorrent

# -------------
# Check for supported OS
# -------------
- name: all | ensure remote os supported
  fail: "Unsupported pkg mgr. This role is depends on apt or yum."
  when: ansible_pkg_mgr not in ['apt', 'yum']


# -------------
# Install rTorrent
# -------------
- name: "apt | ensure rTorrent present"
  sudo: Yes
  apt: name=rtorrent state=present update_cache=no
  when: ansible_pkg_mgr == 'apt'


- name: "yum | ensure rTorrent present"
  sudo: Yes
  yum: name=rtorrent state=present
  when: ansible_pkg_mgr == 'yum'


# -------------
# Configure rTorrent
# -------------
- name: all | ensure torrent folders exist
  file: path={{item}} state=directory
  with_items:
   - "{{ rtorrent_directory_watch }}"
   - "{{ rtorrent_directory_session }}"
   - "{{ rtorrent_directory_download }}"


- name: all | ensure ~/.rtorrent.rc configured
  template: src=rtorrent.rc.j2 dest=~/.rtorrent.rc

