---
# file: roles/rtorrent/tasks/main.yml

# -------------
# Check for supported OS
# -------------
- name: All    | ensure remote os supported
  fail: Unsupported OS. This role is intended for Debian and RedHat based OSs
  when: "'{{ ansible_os_family }}' not in ['Debian', 'RedHat']"


# -------------
# Install rTorrent
# -------------
- name: "Debian | ensure rTorrent present"
  sudo: Yes
  apt: name=rtorrent state=present update_cache=no
  when: ansible_os_family == 'Debian'


- name: "RedHat | ensure rTorrent present"
  sudo: Yes
  yum: name=rtorrent state=present
  when: ansible_os_family == 'RedHat'


# -------------
# Configure rTorrent
# -------------
- name: All    | ensure torrent folders exist
  file: path={{item}} state=directory
  with_items:
   - "{{ rtorrent_directory_watch }}"
   - "{{ rtorrent_directory_session }}"
   - "{{ rtorrent_directory_download }}"


- name: All    | ensure the rtorrent configuration file has user settings
  template: src=rtorrent.rc.j2 dest=~/.rtorrent.rc

