---
# file: roles/rtorrent/tasks/main.yml

# -------------
# Install rTorrent
# -------------
- name: Debian | ensure rTorrent installed
  sudo: Yes
  apt: name={{item}} state=present update_cache=no
  with_items:
   - rtorrent

# -------------
# Configure rTorrent
# -------------
- name: All    | ensure torrent folders exist
  file: path={{item}} state=directory
  with_items:
   - "{{ rtorrent_directory_watch }}"
   - "{{ rtorrent_directory_session }}"
   - "{{ rtorrent_directory_download }}"

- name: All    | ensure the rtorrent configuration file has user settings
  template: src=rtorrent.rc.j2 dest=~/.rtorrent.rc