---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: ansible-ubuntu-16-04
    image: ubuntu:16.04
  - name: ansible-ubuntu-lts
    image: ubuntu:18.04
  - name: ansible-ubuntu-18-10
    image: ubuntu:18.10
  - name: ansible-debian
    image: debian:latest
  - name: ansible-arch
    image: archimg/base:full
    command: /lib/systemd/systemd
    privileged: true
  - name: ansible-fedora
    image: fedora:latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

# vim: set ts=2 sw=2:
